export const QWENPAW_BUILTIN_ROUTES = [
  "/chat",
  "/coding",
  "/channels",
  "/sessions",
  "/inbox",
  "/cron-jobs",
  "/heartbeat",
  "/skills",
  "/skill-pool",
  "/tools",
  "/mcp",
  "/acp",
  "/ACP",
  "/workspace",
  "/agents",
  "/models",
  "/environments",
  "/agent-config",
  "/security",
  "/token-usage",
  "/agent-stats",
  "/voice-transcription",
  "/debug",
  "/backups",
  "/plugin-manager",
  "/",
] as const;
